server:
  port: 3000

spring:
  jpa:
      show-sql: true 
      hibernate:
        ddl-auto: update
  datasource:
    url: jdbc:mysql:localhost:3306/app_albums_java
    username: root
    password: ""
    driver-class-name:
    